### ISSUE TITLE
Doesn't change at startup fedora 25

### ISSUE THREAD

**Issue by gtomas41** [UtkarshGpta/bing-desktop-wallpaper-changer#58]
Installed as instructed, runs manually, doesn't change on startup, or the next day, wallpaper remains the same.

Using Fedora 25 and gnome.

**Comment by gtomas41** [comment]
This is what happens:

```
Installing...


In order to prevent errors and run Bing-Desktop-Wallpaper-Changer, we need to install python-lxml python-bs4 python-gi python-gi-cairo
You only need to install them once.
sudo: apt-get: command not found

Installing in /root/bing-desktop-wallpaper-changer...
'bin' -> '/root/bing-desktop-wallpaper-changer/bin'
'bin/Bing.svg' -> '/root/bing-desktop-wallpaper-changer/bin/Bing.svg'
'bin/Ubuntu.svg' -> '/root/bing-desktop-wallpaper-changer/bin/Ubuntu.svg'
'bin/bing-desktop-wallpaper-changer.desktop' -> '/root/bing-desktop-wallpaper-changer/bin/bing-desktop-wallpaper-changer.desktop'
'bin/main.py' -> '/root/bing-desktop-wallpaper-changer/bin/main.py'
'bin/startup.png' -> '/root/bing-desktop-wallpaper-changer/bin/startup.png'
'installer.sh' -> '/root/bing-desktop-wallpaper-changer/installer.sh'
'LICENSE' -> '/root/bing-desktop-wallpaper-changer/LICENSE'
'README.md' -> '/root/bing-desktop-wallpaper-changer/README.md'
'/root/bing-desktop-wallpaper-changer/bin/main.py' -> '/root/bing-desktop-wallpaper-changer/main.py'

Creating symlink for easy execution...
/root/bing-desktop-wallpaper-changer/main.py symlinked in /usr/bin/bingwallpaper

Adding bing-desktop-wallpaper-changer in Startup Application...
'/root/bing-desktop-wallpaper-changer/bin/bing-desktop-wallpaper-changer.desktop' -> '/root/.config/autostart/bing-desktop-wallpaper-changer.desktop'
cp: cannot create regular file '/root/.config/autostart/bing-desktop-wallpaper-changer.desktop': No such file or directory

Setting icons...
'/root/bing-desktop-wallpaper-changer/bin/Bing.svg' -> '/root/bing-desktop-wallpaper-changer/icon.svg'
Icon set as Bing.

Setting scripts...

Removing unneeded things...
removed '/root/bing-desktop-wallpaper-changer/bin/Bing.svg'
removed '/root/bing-desktop-wallpaper-changer/bin/startup.png'
removed '/root/bing-desktop-wallpaper-changer/bin/Ubuntu.svg'
removed '/root/bing-desktop-wallpaper-changer/bin/bing-desktop-wallpaper-changer.desktop'
removed directory '/root/bing-desktop-wallpaper-changer/bin'
rm: cannot remove '/root/bing-desktop-wallpaper-changer/.gitignore': No such file or directory

Executing bing-desktop-wallpaper-changer...
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
./installer.sh: line 332:  9365 Segmentation fault      (core dumped) python $LINKTO/$TERMNAME
```

**Comment by utkarshgpta** [comment]
@nks15

**Comment by ghost** [comment]
### I think that the problem is this:

The installer is optimized to run on *buntu-based distro with GNOME.
(I'm currently using Ubuntu GNOME and BDWC runs well on it)
It uses _'apt'_ to install python packages that BDWC needs.

Fedora does not use _'dpkg'_ and _'apt'_. (as far as I know, Fedora uses _rpm_)
and I think that the system is slightly different in Fedora.

Someday I will add Fedora support in the Installer but I'm not sure when :(

-----

Anyway,
1) you need to install these packages manually using _rpm_
**python-lxml python-bs4 python-gi python-gi-cairo**

2) uninstall BDWC (to clean up the system)
_sudo ./installer.sh --uninstall_

3) install BDWC again
_sudo ./installer.sh --install_

4) you need to add BDWC in Startup Applications manually (Below was in the old README)
**Autostart with ~/.config/autostart**

If you run gnome 3 from Fedora, you have to create the file

_/[user]/.config/autostart/bing-desktop-wallpaper-changer.desktop_

the file contents look like:

[Desktop Entry]
Type=Application
Terminal=false
Exec=_/path/to_/main.py
Name=Bing Desktop Wallpaper Changer

**Replace [user] with your actual user directory and _/path/to/_ with your actual parent directory for the bing-desktop-wallpaper-changer directory.**

5) If BDWC not auto-starts when you log-in, you can open up the Terminal and run
_bingwallpaper_ or _python /bdwc/installed/full_path_/main.py_

6) Feedback/notify me with full installation details (I need to know that this method works or not)

**Comment by ghost** [comment]
In theory, it should be able to install in most Linux distros because it examines whether apt, pip or yum is available.

Please try again. @UtkarshGpta @gtomas41
