### ISSUE TITLE
Keep only the last downloaded image

### ISSUE THREAD

**Issue by adrhc** [UtkarshGpta/bing-desktop-wallpaper-changer#74]
The downloaded image is not set as wallpaper automatically so the user have to use other meanings in order to select it as the current wallpaper. While this might not be the purpose of this software it could help here by simply leaving into the downloaded directory only the last fetched image. This could be also made configurable within ~/.config/bing-desktop-wallpaper-changer/config.ini with a property e.g. _keep_only_last_count_; then the user could simply set keep_only_last_count=1 in order to keep only the last downloaded image (dir_max_size won't help here).

**Comment by utkarshgpta** [comment]
Hello @adrhc normally the downloaded image would automatically be set as the current wallpaper - that's the motivation behind this small project xD
Can you please mention the LInux distribution you're using this on? Since this requires GNOME desktop environment so as to run in the desired manner, your Linux distribution might not support this. If that's the case, you can fork this repository, make changes to the command responsible for changing the wallpaper so that other people wanting this functionality can use this too. Cheers!

**Comment by utkarshgpta** [comment]
Closed issue due to inactivity.
